version: "3.7"

services:
    mongodb:
        image: mongo:latest
        ports:
            - 27017:27017
        volumes:
            - mongodb:/data/db
        networks:
            - app-network

    redis:
        image: redis:latest
        ports:
            - 6379:6379
        networks:
            - app-network

    node-app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        depends_on:
            - mongodb
            - redis
        container_name: myapp-node-server
        env_file:
            - ./.env
        environment:
            - PORT=3000
            - MONGODB_URI=mongodb://mongodb:27017/likesdb
            - DB_NAME=likesdb
            - REDIS_URL=redis:6379
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    mongodb:
